# Generated by Django 3.1.2 on 2020-12-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=25)),
                ('subservice', models.CharField(max_length=25)),
                ('payment', models.IntegerField()),
                ('advance', models.IntegerField(default=0)),
                ('priority', models.CharField(max_length=6)),
                ('status', models.CharField(default='Due', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
