# Generated by Django 3.1.2 on 2020-11-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0003_extenduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendUser',
        ),
    ]
