# Generated by Django 3.1.2 on 2020-11-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0006_auto_20201119_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=25)),
                ('sub_service', models.CharField(max_length=25)),
                ('payment', models.IntegerField()),
                ('adv_payment', models.IntegerField()),
                ('priority', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
