# Generated by Django 3.1.2 on 2020-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='heading',
            field=models.CharField(default='This is heading', max_length=50),
            preserve_default=False,
        ),
    ]
