# Generated by Django 3.1.2 on 2020-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0010_image_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='heading',
            field=models.CharField(max_length=30),
        ),
    ]
