# Generated by Django 3.1.2 on 2020-12-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0014_serviceimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimage',
            old_name='service_id',
            new_name='service',
        ),
    ]
