# Generated by Django 3.1.2 on 2020-12-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0015_auto_20201223_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='emitr.service'),
        ),
    ]
