# Generated by Django 3.1.2 on 2020-12-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0016_auto_20201223_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='fee',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emitr.service'),
        ),
    ]
