# Generated by Django 3.1.2 on 2020-12-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0018_auto_20201227_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subservice',
            old_name='service_id',
            new_name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='isExclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ExtendUser',
        ),
    ]
