# Generated by Django 3.1.2 on 2020-12-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0019_auto_20201230_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
