# Generated by Django 3.1.2 on 2020-12-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0020_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='ExclusiveDescription',
        ),
    ]
