# Generated by Django 3.1.2 on 2020-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0021_auto_20201230_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
