# Generated by Django 3.1.2 on 2020-12-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0023_auto_20201230_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
