# Generated by Django 3.1.2 on 2020-12-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0024_auto_20201230_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
