# Generated by Django 3.1.2 on 2020-12-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0025_auto_20201230_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/service'),
        ),
    ]
