# Generated by Django 3.1.2 on 2020-12-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0026_auto_20201230_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExclusivePost',
        ),
        migrations.AlterField(
            model_name='service',
            name='ExclusiveDescription',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
